# Generated by Django 4.2.17 on 2024-12-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name_plural': 'categories'},
        ),
    ]
